# Generated by Django 5.2 on 2025-04-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_remove_service_location_service_image_service_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='location',
            field=models.CharField(default='', max_length=100, verbose_name='Город'),
        ),
    ]
