# Generated by Django 5.2 on 2025-04-26 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_service_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
    ]
