# Generated by Django 5.2 on 2025-05-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_message_is_read_userprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Категория'),
        ),
    ]
