# Generated by Django 5.2 on 2025-05-13 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_rename_timestamp_message_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='recipient',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='message',
            name='service',
        ),
    ]
