# Generated by Django 5.2 on 2025-05-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_rename_recipient_message_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
